"""PDF report generator for OneClient Intelligence answers."""

import re
from datetime import datetime, timezone
from pathlib import Path

from fpdf import FPDF

BMO_BLUE = (0, 121, 193)
TEXT_PRIMARY = (26, 26, 46)
TEXT_SECONDARY = (90, 106, 122)
BORDER_LIGHT = (226, 232, 240)

_LOGO_PATH = Path(__file__).resolve().parent.parent / "app" / "assets" / "bmo_wm_logo.png"


def _md_to_html(md: str) -> str:
    """Minimal markdown → fpdf2-compatible HTML conversion."""
    lines = md.split("\n")
    html_parts = []
    in_list = False
    in_table = False
    table_headers = []

    for line in lines:
        stripped = line.strip()

        if not stripped:
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            if in_table:
                html_parts.append("</table>")
                in_table = False
            html_parts.append("<br>")
            continue

        if stripped.startswith("|") and stripped.endswith("|"):
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            if all(re.match(r"^[-:]+$", c) for c in cells):
                continue
            if not in_table:
                in_table = True
                table_headers = cells
                html_parts.append(
                    '<table border="1" cellpadding="4" cellspacing="0" width="100%">'
                )
                html_parts.append("<thead><tr>")
                for cell in cells:
                    html_parts.append(f"<th>{_inline_fmt(cell)}</th>")
                html_parts.append("</tr></thead>")
            else:
                html_parts.append("<tr>")
                for cell in cells:
                    html_parts.append(f"<td>{_inline_fmt(cell)}</td>")
                html_parts.append("</tr>")
            continue

        if in_table:
            html_parts.append("</table>")
            in_table = False

        if stripped.startswith("# "):
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f"<h1>{_inline_fmt(stripped[2:])}</h1>")
        elif stripped.startswith("## "):
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f"<h2>{_inline_fmt(stripped[3:])}</h2>")
        elif stripped.startswith("### "):
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f"<h3>{_inline_fmt(stripped[4:])}</h3>")
        elif stripped.startswith("- ") or stripped.startswith("* "):
            if not in_list:
                html_parts.append("<ul>")
                in_list = True
            html_parts.append(f"<li>{_inline_fmt(stripped[2:])}</li>")
        elif re.match(r"^\d+\.\s", stripped):
            content = re.sub(r"^\d+\.\s", "", stripped)
            if not in_list:
                html_parts.append("<ul>")
                in_list = True
            html_parts.append(f"<li>{_inline_fmt(content)}</li>")
        else:
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f"<p>{_inline_fmt(stripped)}</p>")

    if in_list:
        html_parts.append("</ul>")
    if in_table:
        html_parts.append("</table>")

    return "\n".join(html_parts)


_UNICODE_MAP = {
    "—": "--", "–": "-", "‘": "'", "’": "'",
    "“": '"', "”": '"', "…": "...", "•": "*",
    "→": "->", "←": "<-", "↔": "<->",
    "≥": ">=", "≤": "<=", "≠": "!=",
    "×": "x", "÷": "/", "−": "-",
    "✓": "[x]", "✗": "[ ]", "·": "*",
}


def _sanitize(text: str) -> str:
    for char, replacement in _UNICODE_MAP.items():
        text = text.replace(char, replacement)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _inline_fmt(text: str) -> str:
    """Convert bold and italic markdown to HTML."""
    text = _sanitize(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"\*(.+?)\*", r"<i>\1</i>", text)
    text = re.sub(r"`(.+?)`", r"<b>\1</b>", text)
    return text


class _ReportPDF(FPDF):
    def header(self):
        if _LOGO_PATH.exists():
            self.image(str(_LOGO_PATH), x=15, y=10, h=10)
            self.set_x(50)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*BMO_BLUE)
        self.cell(0, 10, "OneClient Intelligence", align="L")
        self.ln(14)
        self.set_draw_color(*BMO_BLUE)
        self.set_line_width(0.5)
        self.line(15, self.get_y(), self.w - 15, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*TEXT_SECONDARY)
        self.cell(0, 10, "Generated by OneClient Intelligence", align="L")
        self.cell(0, 10, f"Page {self.page_no()}", align="R")


def build_report(question: str, answer: str) -> bytes:
    """Build a branded PDF report and return the raw bytes."""
    pdf = _ReportPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*TEXT_PRIMARY)
    pdf.cell(0, 7, "Question", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*TEXT_SECONDARY)
    pdf.multi_cell(0, 6, _sanitize(question))
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*TEXT_SECONDARY)
    timestamp = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
    pdf.cell(0, 5, timestamp, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_draw_color(*BORDER_LIGHT)
    pdf.set_line_width(0.3)
    pdf.line(15, pdf.get_y(), pdf.w - 15, pdf.get_y())
    pdf.ln(6)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*TEXT_PRIMARY)
    html = _md_to_html(answer)
    pdf.write_html(html)

    return bytes(pdf.output())
